<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.context.test' shared service.

return $this->privates['security.firewall.map.context.test'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () {
    yield 0 => ($this->privates['security.channel_listener'] ?? $this->load('getSecurity_ChannelListenerService.php'));
    yield 1 => ($this->privates['security.context_listener.0'] ?? $this->load('getSecurity_ContextListener_0Service.php'));
    yield 2 => ($this->privates['security.authentication.listener.basic.test'] ?? $this->load('getSecurity_Authentication_Listener_Basic_TestService.php'));
    yield 3 => ($this->privates['security.access_listener'] ?? $this->load('getSecurity_AccessListenerService.php'));
}, 4), ($this->privates['security.exception_listener.test'] ?? $this->load('getSecurity_ExceptionListener_TestService.php')), NULL, ($this->privates['security.firewall.map.config.test'] ?? $this->load('getSecurity_Firewall_Map_Config_TestService.php')));
